<a href="https://colab.research.google.com/github/blenassefa2/Machine_Learning_A2SV/blob/main/Checkpoints.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Checkpoints

**CP1**:
Given the list $[A, B, C]$, use the `itertools` module to generate all possible
combinations of 2 elements.

**Expected Output**:
$$
 (A, B) \\
 (A, C) \\
 (B, C)
$$

In [1]:
import itertools

lst = ['A', 'B', 'C']
combinations = list(itertools.combinations(lst, 2))

print(combinations)


[('A', 'B'), ('A', 'C'), ('B', 'C')]


**CP2**:
Use the `itertools` module to create a sequence that cycles through
['Python', 'is', 'fun'] infinitely. Print the first 10 elements of the sequence.

**Expected Output**:
$$
Python \\
is\\
fun\\
Python\\
is\\
fun\\
Python\\
is\\
fun\\
Python
$$

In [2]:
import itertools

sequence = itertools.cycle(['Python', 'is', 'fun'])

for _ in range(10):
    element = next(sequence)
    print(element)


Python
is
fun
Python
is
fun
Python
is
fun
Python


**CP3**:
Use the `glob` module to list all python (.py) files in your current working directory.




In [3]:
import glob

python_files = glob.glob("*.py")

for file in python_files:
    print(file)


**CP4**: You are given the following HTML content below. Write a function that uses BeautifulSoup to parse the HTML and extract the text inside the   '$<p>$'   tag.


In [5]:
#<html><body><div class='main'><h1>Welcome to AI</h1><p>AI is transforming the world</p></div></body></html>

In [4]:
from bs4 import BeautifulSoup

def extract_paragraph_text(html_content):
    soup = BeautifulSoup(html_content, 'html.parser')
    paragraph_tags = soup.find_all('p')
    text_list = [tag.get_text() for tag in paragraph_tags]
    return text_list

# Example usage
html_content = "<html><body><div class='main'><h1>Welcome to AI</h1><p>AI is transforming the world</p></div></body></html>"
paragraph_text = extract_paragraph_text(html_content)
print(paragraph_text)


['AI is transforming the world']


**CP5**: Write a function that uses the re module to replace all occurrences of the word "AI" with "Artificial Intelligence" in a given text.

In [6]:
import re

def replace_word(text):
    updated_text = re.sub(r'\bAI\b', 'Artificial Intelligence', text)
    return updated_text

# Example usage
text = "AI is changing the world. The field of AI is rapidly advancing."
updated_text = replace_word(text)
print(updated_text)


Artificial Intelligence is changing the world. The field of Artificial Intelligence is rapidly advancing.


**CP6**: Create a numpy array of 10 zeros.

In [7]:
import numpy as np

zeros_array = np.zeros(10)

print(zeros_array)


[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


**CP7** Create a numpy array of the integers from 10 to 49.

In [8]:
import numpy as np

array = np.arange(10, 50)

print(array)


[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


**CP8**: Create a 3x3 numpy matrix, filled with values ranging from 0 to 8.

In [9]:
import numpy as np

matrix = np.arange(9).reshape((3, 3))

print(matrix)


[[0 1 2]
 [3 4 5]
 [6 7 8]]


**CP9**: Explain why machine learning models require large amounts of data? What does it mean for an amount of data to be **large**?

In [ ]:
Machine learning models require large amounts of data for several reasons. Firstly, a large dataset provides more diverse examples, allowing the model to learn a wider range of patterns and variations in the data. This enhances the model's ability to generalize and make accurate predictions on new, unseen data. Secondly, a large dataset helps in training complex models with a large number of parameters. More data enables the model to capture intricate relationships and complex functions, improving its overall performance. Additionally, a large dataset reduces the risk of overfitting by preventing the model from memorizing the training data and instead focusing on learning more robust and generalizable patterns. In essence, a large dataset facilitates better generalization, improves model flexibility, and reduces the variance, leading to more accurate and reliable machine learning models.

**CP10**: Explain 2 ways AI can be used in an adverserial way, and what can be done to prevent it.

In [ ]:
AI can be used in adversarial ways, such as automating attack methods like denial-of-service attacks, and engaging in scams by impersonating real individuals or organizations. To prevent such adversarial use of AI, it is crucial to enhance our understanding of the technology and proactively address potential attack vectors. This includes investing in robust security measures, conducting regular vulnerability assessments, and promptly patching known vulnerabilities. Additionally, implementing rigorous authentication protocols, developing advanced anomaly detection systems, and fostering ethical AI practices can help prevent and mitigate the risks associated with adversarial AI applications.